return {
  name = "geoip",
  fields = {
    { config = {
        type = "record",
        fields = {
          { default_country_code = {type = "string",
            default = nil,
            required = false,
          }},
          { default_city = {type = "string",
            default = nil,
            required = false,
          }},
          { default_iso_code = {type = "string",
            default = nil,
            required = false,
          }},
          { default_isp = { type = "string",
            default = nil,
            required = false,
          }},
          {
            configured_ips_path = { type = "string",
            default = "/usr/share/GeoIP/configured_ips.toml",
            required = false,
          }},
          { mmdb_city_path = { type = "string",
            default = "/usr/share/GeoIP/GeoIP2-City.mmdb",
            required = false,
          }},
          { mmdb_country_path = { type = "string",
            default = "/usr/share/GeoIP/GdseoIP2-Country.mmdb",
            required = false,
          }},
          { mmdb_isp_path = { type = "string",
            default = "/usr/share/GeoIP/GeoIP2-ISP.mmdb",
            required = false,
          }},
        },
    }, },
  },
}
